### PR TITLE
Add test for RtlCompareMemory

### PR DESCRIPTION
**Pull request by Fisherman166**
Added a simple test for RtlCompareMemory. Also added back in the Av tests that are not causing the crash on Cxbx.

### CODE REVIEW

**Comment by PatrickvL** [comment]
Thanks!

Could you also indicate which tests still fail on Cxbx-Reloaded? And possibly attach a dump of the output from a real machine?

**Comment by Luca1991** [comment]
@Fisherman166 @PatrickvL the Av tests, in the current form, causes real hardware to crash. It is better to disable them for now, until I (or Fisherman) fix the address (that should be 0xFD000000 as pointed out by Patrick).

**Comment by PatrickvL** [comment]
... Which should be declared as NV2A_MMIO_BASE

**Comment by Fisherman166** [comment]
test_AvSetDisplayMode is the one that fails on the Cxbx. All of the Av tests are always skipped on real hardware. Luca wrote all of the AV tests, so he would be better suited to to work on fixing them for now.

**Comment by Luca1991** [comment]
Ok good, I'll give it a look ;) Anyway these tests shouldn't be skipped on real hw after the fix.

**Pull request merged**
